# Generated by Django 4.0.2 on 2022-02-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_alter_staff_address_alter_staff_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['start_date']},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.AlterField(
            model_name='staff',
            name='id_card',
            field=models.CharField(default=1000, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.IntegerField(default=222),
            preserve_default=False,
        ),
    ]
